# Generated by Django 3.2.4 on 2021-07-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2020-08-31 10:12:13'),
            preserve_default=False,
        ),
    ]
